### ISSUE TITLE
ImportError: No module named 'html2docx'

### ISSUE THREAD

**Issue by elaa0505** [erezlife/html2docx#47]
Hi,
  I have facing some problem after installed the html2docx package
Error :
Traceback (most recent call last):
  File "file.py", line 1, in <module>
    from html2docx import html2docx
ImportError: No module named 'html2docx'

any1 can give solution for the issue

**Comment by francoisfreitag** [comment]
Maybe your python environment is not configured correctly. How did you install html2docx? Can you provide the list of command that trigger this error?

The following works in my environment:
```
$ python -m venv venv
$ source venv/bin/activate
$ venv/bin/pip install html2docx
$ venv/bin/python
Python 3.8.1 (default, Dec 21 2019, 20:57:38) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import html2docx
>>> 
```

**Comment by elaa0505** [comment]
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import html2docx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'html2docx'
>>>

**Comment by elaa0505** [comment]
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import html2docx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'html2docx'
>>>

**Comment by francoisfreitag** [comment]
In order to help you, I need to know how you installed `html2docx`? Can you give all the steps you’ve taken to go from a clean environment to see this error?

Besides, I see in the prompt that Python 3.5 is used. This version is not supported by html2docx, only version 3.6 and later are supported. See https://github.com/erezlife/html2docx/blob/master/setup.cfg#L30.

**Comment by elaa0505** [comment]
@francoisfreitag thank you..!

**Comment by francoisfreitag** [comment]
The issue appears to be solved.

**Comment by elaa0505** [comment]
yes @francoisfreitag
