### ISSUE TITLE
Support for page break

### ISSUE THREAD

**Issue by amberdiehl** [erezlife/html2docx#53]
Greetings!

Is there anyway to define in the HTML where to induce a page break in the word document?

Additional information--I looked at html2docx.py and there appears to be a check for breaks. I have verified that code is executing (was not originally as the `<br>` tag was not inside a paragraph). 

Is there a reason this:
```
elif tag == "br":
if self.r:
self.r.add_break()
```
is not:
```
elif tag == "br":
if self.r:
self.doc.add_page_break()
```
I just tested that and it worked. If nothing else, I'll subclass and modify locally.

Thanks in advance,
Amber

**Comment by roman-danilov** [comment]
HTML does not have a way set a page break as far as I know. You can set a page break with CSS in `@media print` section and then process that. It's not supported in the current html2docx code.

**Comment by amberdiehl** [comment]
Hi @roman-danilov, thanks for the speedy reply! Yes, I tried the CSS @media print thinking maybe that would be interpreted by html2docx as a page break. Finally looked at the code and realized not so much. Thanks for confirming it's currently not supported--would be a great feature to add. 

I was successful in monkey patching the code as shown above, so onward.

Thanks for your help!
