### ISSUE TITLE
p tag in li doesn't seem to work properly

### ISSUE THREAD

**Issue by louking** [erezlife/html2docx#60]
When I put p tags within li, each p tag seems to create another li for the output document. I may be willing to work on a pr for this, if you give me any suggestion on what to look at. (I'm actually trying to achieve something else*, and may be able to avoid going through a docx file, which is why I say "may be willing to work on...").

Example input / output files enclosed. For now you can ignore the css which seems to make its way into the output file as text.

The problem is seen under the Action Item Summary heading.

[2020-12-07-fsrc-board-meeting-minutes.zip](https://github.com/erezlife/html2docx/files/6173145/2020-12-07-fsrc-board-meeting-minutes.zip)

\* I'm ultimately trying to upload something to google drive to create a google doc. Going directly from html has been working fine, but I recently discovered that the google drive api doesn't seem to process the img tag correctly. That may be because during my testing this tag is pointing at my local machine. In any case, I have been considering to go via the docx file for other formatting reasons.

**Comment by francoisfreitag** [comment]
Hi, thanks for reporting. This is indeed unexpected behavior. I believe #61 should solve the issue.
