### ISSUE TITLE
"Font" object has no attribute "class"

### ISSUE THREAD

**Issue by n8chz** [erezlife/html2docx#63]
First attempt to use. Made [the sample code](https://pypi.org/project/html2docx/) into a script:
```python
#!/usr/bin/python3

# adapted from https://pypi.org/project/html2docx/

from html2docx import html2docx
import sys

for a in sys.argv[1:]:
    b = a
    if a.endswith(".html"):
        b = a[:-5]
    else:
        a += ".html"

    with open(a) as fp:
        html = fp.read()

    # html2docx() returns an io.BytesIO() object. The HTML must be valid.
    buf = html2docx(html, title="Converted from HTML with html2docx")

    with open(b+".docx", "wb") as fp:
        fp.write(buf.getvalue())
```
My first run of the script on [this HTML](https://pastebin.com/BRfbkVST) produced this:

> $ html2docx final
> Traceback (most recent call last):
>   File "/usr/local/bin/html2docx", line 19, in <module>
>     buf = html2docx(html, title="Converted from HTML with html2docx")
>   File "/home/lori/.local/lib/python3.8/site-packages/html2docx/__init__.py", line 11, in html2docx
>     parser.feed(content.strip())
>  File "/usr/lib/python3.8/html/parser.py", line 111, in feed
>    self.goahead(0)
>   File "/usr/lib/python3.8/html/parser.py", line 163, in goahead
>     self.handle_data(unescape(rawdata[i:j]))
>   File "/home/lori/.local/lib/python3.8/site-packages/html2docx/html2docx.py", line 211, in handle_data
>     self.add_text(data)
>   File "/home/lori/.local/lib/python3.8/site-packages/html2docx/html2docx.py", line 130, in add_text
>     setattr(self.r.font, font_attr, value)
> AttributeError: 'Font' object has no attribute 'class'

**Comment by francoisfreitag** [comment]
Thanks for reporting the issue, that’s indeed a bug in html2docx.
Can you confirm https://github.com/erezlife/html2docx/pull/64 fixes it?

**Comment by francoisfreitag** [comment]
The [provided document](https://pastebin.com/BRfbkVST) is now converted to a docx. Assuming the issue is fixed, feel free to reopen if the issue isn’t fixed for you.
