### ISSUE TITLE
height_attr error

### ISSUE THREAD

**Issue by Fikralaksana** [erezlife/html2docx#67]
File "/usr/lib/python3.6/html/parser.py", line 345, in parse_starttag
    self.handle_starttag(tag, attrs)
  File "env/lib/python3.6/site-packages/html2docx/html2docx.py", line 172, in handle_starttag
    self.add_picture(attrs)
  File "env/lib/python3.6/site-packages/html2docx/html2docx.py", line 144, in add_picture
    height_px = int(height_attr) if height_attr else None
ValueError: invalid literal for int() with base 10: '428px'

int() convert problem??

**Comment by idriscahyono** [comment]
add 
`    height_attr = height_attr.replace('px','')
    width_attr = height_attr.replace('px','')`
in the function add_picture in html2docx.py (site-packages)

**Comment by Fikralaksana** [comment]
any other solution? that doesn't need to change the package?

**Comment by francoisfreitag** [comment]
The HTML document is invalid. The height (and width) attributes must be integers without units. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#attr-height

The precondition for `html2docx` is that the provided HTML is valid.
